GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email":"langdonhp435@gmail.com",
  "password":"123456"
}

###
POST http://lawebdepoza.herokuapp.com/api/auth/login
Content-Type: application/json

{
  "email":"langdonhp435@gmail.com",
  "password":"123456"
}

###