

GET  http://localhost:8081/api/categories
###
GET  https://lawebdepoza.herokuapp.com/api/categories?from=11&&limit=2
###

GET  http://localhost:8080/api/categories/61bbd3ec7232a4b824259922
###

POST http://localhost:8080/api/categories
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWJiODU1NWEwYjJkN2FiNTVjZmYyNjMiLCJpYXQiOjE2Mzk2OTE0NzQsImV4cCI6MTYzOTcwNTg3NH0._Ov--OSuPzfL3GnhAuJ78jpQI5gEde11wFqO2OqbIgE

{
  "name": "mercado"
}

###

PUT  http://localhost:8080/api/categories/61bbd3ec7232a4b824259922
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWJiODU1NWEwYjJkN2FiNTVjZmYyNjMiLCJpYXQiOjE2Mzk3NjE2ODksImV4cCI6MTYzOTc3NjA4OX0.SxPEtTXlSmDS-WhvtrZWmdC3cLnmVHKaAd-SnXnRkgk

{
  "name": "comida"
}
###
DELETE  http://localhost:8080/api/categories/61bbd3ec7232a4b824259922
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWJiODU1NWEwYjJkN2FiNTVjZmYyNjMiLCJpYXQiOjE2Mzk3NjE2ODksImV4cCI6MTYzOTc3NjA4OX0.SxPEtTXlSmDS-WhvtrZWmdC3cLnmVHKaAd-SnXnRkgk

###