
GET http://localhost:8080/api/places
###
GET http://localhost:8080/api/places/61bbe24dec8bd1459533e844
###
POST http://localhost:8080/api/places
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWJiODU1NWEwYjJkN2FiNTVjZmYyNjMiLCJpYXQiOjE2NDA3MTgwNDEsImV4cCI6MTY0MDczMjQ0MX0.O-BGAkOYqlV1wDNYTqAvwb_m7SRGRD21uIJ4g0ZNcPA

{
  "name":"La Kanija",
  "description":"Bar y discoteca abrimos desde las 3 P.M. hasta qu el ultimo cliente se vaya, bar, snacks, alitas, buena música y excelente atención, visitanos",
  "address":"Av. Ejército Mexicano esq. Tamaulipas, Plan de Ayala, Tihuatlan C.P. 92912",
 "category":"61bbd4880c4bae8d8f44a39c"
}
###

PUT http://localhost:8080/api/places/61bbe24dec8bd1459533e844
Content-Type: application/json

{
  "facebook":"https://www.facebook.com"
}

###

GET https://lawebdepoza.vercel.app/api/places
###
GET https://lawebdepoza.vercel.app/api/places/61bbe24dec8bd1459533e844
###